class Constants:
    REGISTER_EXIST_EMAIL = "This email is already been used"
    REGISTER_FAIL_MESSAGE = "Register user fail"
    EMPTY_FEEDBACK_MESSAGE = "This field is required"
    EMPTY_LOGIN_MESSAGE = "Please fill all required fields"
    LOGIN_FAIL_MESSAGE = "User name or password is incorrect"
    USERMAIL_FEEDBACK_MESSAGE = "User mail not match the pattern"
    PASSWORD_FEEDBACK_MESSAGE = "Password not match the pattern"
    REPASSWORD_FEEDBACK_MESSAGE = "Re-password not match the password"
    PHONE_FEEDBACK_MESSAGE = "Phone not match the pattern"
    DISCOUNT_FEEDBACK_MESSAGE = "Discout not match the pattern"
    EMAIL_REGEX = "^[A-Z0-9_a-z]+@[A-Z0-9\\.a-z]+\\.[A-Za-z]{2,6}$"
    PASSWORD_REGEX = "[a-zA-Z0-9_!@#$%^&*]{3,}"
    PHONE_REGEX = "^\\d+$"
    DISCOUNT_REGEX = "^[A-Z0-9]*$"
