# Generated by Django 4.2.8 on 2023-12-18 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('mail', models.EmailField(db_column='user_mail', max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('role', models.CharField(db_column='account_role', max_length=255)),
                ('name', models.CharField(db_column='user_name', max_length=255)),
                ('address', models.TextField(db_column='user_address')),
                ('phone', models.CharField(db_column='user_phone', max_length=20)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(db_column='order_id', primary_key=True, serialize=False)),
                ('orderName', models.CharField(db_column='order_name', max_length=255)),
                ('status', models.CharField(db_column='order_status', max_length=255)),
                ('orderDate', models.DateField(db_column='order_date')),
                ('discount', models.CharField(db_column='order_discount_code', max_length=255)),
                ('orderAddress', models.TextField(db_column='order_address')),
                ('userMail', models.ForeignKey(db_column='user_mail', on_delete=django.db.models.deletion.CASCADE,
                                               to='mobilestore.account')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(db_column='product_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='product_name', max_length=255)),
                ('description', models.TextField(db_column='product_des')),
                ('price', models.FloatField(db_column='product_price')),
                ('src', models.URLField(db_column='product_img_source')),
                ('type', models.CharField(db_column='product_type', max_length=255)),
                ('brand', models.CharField(db_column='product_brand', max_length=255)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(db_column='amount_product')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE,
                                            to='mobilestore.order')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE,
                                              to='mobilestore.product')),
            ],
            options={
                'db_table': 'product_order',
            },
        )
    ]
