# Generated by Django 4.2.8 on 2023-12-19 14:51
import csv

from django.db import migrations

from mobilestore.models import Account, Product


def insert_data(apps, schema_editor):
    Account.objects.create(mail='test@gmail.com', password='123', role='USER', name='Test User', address='HCM City',
                           phone='0984578986')

    csv_data = """
    1,iPhone 11 Pro Max 512GB,"Màn hình: 6.5"", Super Retina XDR, HĐH: iOS 13, CPU: Apple A13 Bionic 6 nhân, RAM: 4 GB, ROM: 512 GB, Camera: 3 camera 12 MP, Selfie: 12 MP",43.99,https://cdn.tgdd.vn/Products/Images/42/210654/iphone-11-pro-max-512gb-gold-600x600.jpg,Like New,Apple
    2,iPhone 11 Pro Max 256GB,"Màn hình: 6.5"", Super Retina XDR, HĐH: iOS 13, CPU: Apple A13 Bionic 6 nhân, RAM: 4 GB, ROM: 512 GB, Camera: 3 camera 12 MP, Selfie: 12 MP",37.99,https://cdn.tgdd.vn/Products/Images/42/210653/iphone-11-pro-max-256gb-black-600x600.jpg,New,Apple
    3,iPhone Xs Max 256GB,"Màn hình: 6.5"", Super Retina, HĐH: iOS 12, CPU: Apple A12 Bionic 6 nhân, RAM: 4 GB, ROM: 256 GB, Camera: Chính 12 MP & Phụ 12 MP, Selfie: 7 MP",32.99,https://cdn.tgdd.vn/Products/Images/42/190322/iphone-xs-max-256gb-white-600x600.jpg,Like New,Apple
    4,iPhone X 256GB,"Màn hình: 5.8"", Super Retina, HĐH: iOS 12, CPU: Apple A11 Bionic 6 nhân, RAM: 3 GB, ROM: 256 GB, Camera: Chính 12 MP & Phụ 12 MP, Selfie: 7 MP",27.99,https://cdn.tgdd.vn/Products/Images/42/190324/iphone-xs-256gb-white-600x600.jpg,New,Apple
    5,iPhone Xs 64GB,"Màn hình: 5.8"", Super Retina, HĐH: iOS 12, CPU: Apple A12 Bionic 6 nhân, RAM: 4 GB, ROM: 64 GB, Camera: Chính 12 MP & Phụ 12 MP, Selfie: 7 MP",24.99,https://cdn.tgdd.vn/Products/Images/42/190321/iphone-xs-max-gold-600x600.jpg,Like New,Apple
    6,iPhone Xr 128GB,"Màn hình: 6.1"", Liquid Retina, HĐH: iOS 12, CPU: Apple A12 Bionic 6 nhân, RAM: 3 GB, ROM: 128 GB, Camera: 12 MP, Selfie: 7 MP",17.99,https://cdn.tgdd.vn/Products/Images/42/191483/iphone-xr-128gb-red-600x600.jpg,New,Apple
    7,iPhone Xr 128GB,"Màn hình: 6.1"", Liquid Retina, HĐH: iOS 12, CPU: Apple A12 Bionic 6 nhân, RAM: 3 GB, ROM: 128 GB, Camera: 12 MP, Selfie: 7 MP",17.99,https://cdn.tgdd.vn/Products/Images/42/191483/iphone-xr-128gb-red-600x600.jpg,Like New,Apple
    8,iPhone 8 Plus 64GB,"Màn hình: 5.5"", Retina HD, HĐH: iOS 12, CPU: Apple A11 Bionic 6 nhân, RAM: 3 GB, ROM: 64 GB, Camera: Chính 12 MP & Phụ 12 MP, Selfie: 7 MP",16.59,https://cdn.tgdd.vn/Products/Images/42/114110/iphone-8-plus-hh-600x600.jpg,New,Apple
    9,iPhone 7 Plus 32GB,"Màn hình: 5.5"", Retina HD, HĐH: iOS 12, CPU: Apple A10 Fusion 4 nhân 64-bit, RAM: 3 GB, ROM: 32 GB, Camera: Chính 12 MP & Phụ 12 MP, Selfie: 7 MP",12.49,https://cdn.tgdd.vn/Products/Images/42/78124/iphone-7-plus-32gb-gold-600x600.jpg,Like New,Apple
    10,iPhone 7 32GB,"Màn hình: 4.7"", Retina HD, HĐH: iOS 12, CPU: Apple A10 Fusion 4 nhân 64-bit, RAM: 2 GB, ROM: 32 GB, Camera: 12 MP, Selfie: 7 MP",10.49,https://cdn.tgdd.vn/Products/Images/42/74110/iphone-7-gold-600x600.jpg,New,Apple
    """

    # Read CSV data and insert into database
    csv_reader = csv.reader(csv_data.strip().split('\n'))

    for row in csv_reader:
        id, name, description, price, src, type, brand = row
        Product.objects.create(
            id=id,
            name=name,
            description=description,
            price=float(price),
            src=src,
            type=type,
            brand=brand
        )


class Migration(migrations.Migration):
    dependencies = [
        ('mobilestore', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data),
    ]
